name: Velocity Radar count
on: workflow_dispatch
permissions:
  contents: read
  id-token: write
jobs:
  count:
    uses: AIMLPM/velocity-radar-count/.github/workflows/count.yml@ac79a3daf28835d6ac34d8ccf0576da00fd5be84 # v8
    with:
      timezone: America/Vancouver
    secrets:
      VELOCITY_RADAR_TOKEN: ${{ secrets.VELOCITY_RADAR_TOKEN }}
